config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resources :books, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews

  validates :title, presence: true
  validates :author, presence: true


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book

  validates :rating, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    # render :index
  end

  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews
    @review = Review.new
    # @reviews = Review.where(book_id: @book.id)
  end

  def new
    @book = Book.new
    # render :books/new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path
    else
      render :new
    end

  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :isbn)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @book = Book.find(params[:book_id])
  end

  def create
    # binding.pry
    @book = Book.find(params[:book_id])
    @review = Review.new(review_params)
    @review.book = @book

    if @review.save
      flash[:success] = "Book saved!"
      redirect_to @book
      
      # redirect_to book_path(@book)
      # redirect_to "/books/#{@book.id}"
    else
      # less preferred
      # @errors = @review.errors.full_messages.join(", ")

      # more preferred
      flash.now[:error] = @review.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<h1>Books</h1>

<% @books.each do |book| %>
  <li>
    <%= link_to(book.title, book_path(book)) %>
  </li>

<% end %>

<br>
<%= link_to "Create New Book", new_book_path %>

app/views/books/new.html.erb
<h2>Add a New Book</h2>

<%= form_for(@book) do |f| %>

  <div class="">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  
  <div class="">
    <%= f.label :isbn %>
    <%= f.text_field :isbn %>

  </div>

<%= f.submit %>

<% end %>

app/views/books/show.html.erb
<h2>Book: <%= @book.title %> </h2>
<h4>Author: <%= @book.author %>  </h4>
<p>ISBN: <%= @book.isbn %> </p>

<h3>Reviews: </h3>

<ul>
  <% @reviews.each do |review| %>
    <li>
      <%= review.rating %> | <%= review.body %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a Review", new_book_review_path(@book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goodreads Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if flash.any? %>
      <div class="flash">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: "callout #{name}" %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<h2>Review form for <%= @book.title %> </h2>

<% if @errors %>
  <%= @errors %>
<% end %>

<%= form_for [@book, @review] do |f| %>

  <%= f.label :rating %>
  <%= f.text_field :rating %>

  <%= f.label :body, "Review" %>
  <%= f.text_field :body %>

  <%= f.submit "Add Review" %>

<% end %>